name: Daily Action with My Email

on:
  schedule:
    # Runs at 12:00 UTC (noon) every day
    - cron: "0 12 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  daily-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 23f2000006@ds.study.iitm.ac.in - Display Email
        run: echo "My email address is 23f2000006@ds.study.iitm.ac.in"

      - name: Another example step
        run: echo "GitHub Actions is fun!"